apiVersion: apps/v1
kind: Deployment
metadata:
  name: idan-roman-deployment
spec:
  replicas: 3  # Update the number of replicas here
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
